#!/usr/bin/env bash
# Install and start nginx on my web-01 server. Change home page.
sudo apt update
sudo apt -y install nginx
sudo service nginx restart
echo "Hello World" > /var/www/html/index.nginx-debian.html
