#!/usr/bin/env bash
# Install and start nginx on my web-01 server. Change home page.
sudo apt update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo service nginx restart
