#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# add a custom Nginx response header
sudo apt update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "/^\tserver_name.*/a \\\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/^\tinclude \/etc\/nginx\/sites-enabled\/*/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
