#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
sudo su
if grep "frontend http_front" /etc/haproxy/haproxy.cfg
then
    :
else
    echo -e "\n\nfrontend http_front\nbind *:80\ndefault_backend http_back" | /etc/haproxy/haproxy.cfg
    echo -e "\nbackend http_back\nbalance roundrobin\nserver 3952-web-01 3.89.62.248:80 check\nserver 3952-web-02:80 check" | /etc/haproxy/haproxy.cfg
    echo -e "\nENABLED=1" | /etc/default/haproxy
fi
sudo service haproxy restart
