#!/usr/bin/env bash
# Script that install HAproxi loadblancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 3952-web-01 3.89.62.248:80\n\tserver 3952-web-02 34.230.31.174:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
