#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*
sudo su
echo -e "\n\nfrontend http_front\nbind *:80\nmode http\ndefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\nbalance roundrobin\nserver 3952-web-01 3.89.62.248:80 check\nserver 3952-web-02:80 check" >> /etc/haproxy/haproxy.cfg
#echo -e "\nENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
