#!/usr/bin/env bash
# Bash script that configures the container so that Nginx
# is running as the nginx user
sudo sed -i 's/#user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
