#!/usr/bin/env bash
# Bash script that configures the container so that Nginx
# is running as the nginx user
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx restart
