#!/usr/bin/env bash
# Bash script that configures the container so that Nginx
# is running as the nginx user
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo service nginx restart
